// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using controlleParc;

namespace controlleParc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220314141507_MigrationtableVehicule")]
    partial class MigrationtableVehicule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("controlleParc.Models.Conducteur", b =>
                {
                    b.Property<int>("ConducteurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumPermis")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConducteurID");

                    b.ToTable("Conducteurs");
                });

            modelBuilder.Entity("controlleParc.Models.Vehicule", b =>
                {
                    b.Property<int>("ImmatriculeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Carburant")
                        .HasColumnType("int");

                    b.Property<int?>("ConducteurID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puissance")
                        .HasColumnType("int");

                    b.HasKey("ImmatriculeId");

                    b.HasIndex("ConducteurID");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("controlleParc.Models.Vehicule", b =>
                {
                    b.HasOne("controlleParc.Models.Conducteur", "Conducteur")
                        .WithMany()
                        .HasForeignKey("ConducteurID");

                    b.Navigation("Conducteur");
                });
#pragma warning restore 612, 618
        }
    }
}
